# 第9章 项目启动：用RAG构建你的企业智能知识库
- 09-rag-kickoff/index.qmd
- 09-rag-kickoff/01-why-crisis.qmd
- 09-rag-kickoff/02-how-rag-blueprint.qmd
- 09-rag-kickoff/03-what-rag-concept.qmd
- 09-rag-kickoff/04-toolbox-critical-thinking.qmd 