project:
  type: book
  output-dir: docs

book:
  title: "机器学习：AI驱动的学习与应用"
  author: "陆海波 - 上海应用技术大学 经济与管理学院"
  date: "today"
  chapters:
    - index.qmd
    - part: "序章：新世界的生存法则"
      chapters:
        - 01-welcome/index.qmd
        - 01-welcome/01-not-another-ml-book.qmd
        - 01-welcome/02-ai-conductor.qmd
        - 01-welcome/03-learning-philosophy.qmd
        - 01-welcome/04-what-you-will-get.qmd
        - 02-guide/index.qmd
        - 02-guide/01-golden-circle.qmd
        - 02-guide/02-prompt-engineering.qmd
        - 02-guide/03-first-ai-task.qmd
        - 02-guide/04-ai-learning-coach.qmd
        - 03-environment/index.qmd
        - 03-environment/01-dev-environment.qmd
        - 03-environment/02-ai-copilot-config.qmd
        - 03-environment/03-install-libraries.qmd
    - part: "第一部分：传统机器学习 —— AIGC时代的新应用"
      chapters:
        - 04-project-kickoff/index.qmd
        - 04-project-kickoff/01-why-crisis.qmd
        - 04-project-kickoff/02-how-exploration.qmd
        - 04-project-kickoff/03-what-text-classification.qmd
        - 04-project-kickoff/04-practice-eda.qmd
        - 04-project-kickoff/05-challenge-data-augmentation.qmd
        - 05-text-to-vectors/index.qmd
        - 05-text-to-vectors/01-why-machines-cant-read.qmd
        - 05-text-to-vectors/02-how-exploration-tfidf.qmd
        - 05-text-to-vectors/03-what-tfidf-concept.qmd
        - 05-text-to-vectors/04-practice-feature-engineering.qmd
        - 05-text-to-vectors/05-challenge-beyond-tfidf.qmd
        - 06-first-classifier/index.qmd
        - 06-first-classifier/01-why-first-inspector.qmd
        - 06-first-classifier/02-how-choose-model.qmd
        - 06-first-classifier/03-what-logistic-regression.qmd
        - 06-first-classifier/04-practice-train-predict-evaluate.qmd
        - 06-first-classifier/05-challenge-and-toolbox.qmd
        - 07-model-evaluation/index.qmd
        - 07-model-evaluation/01-why-metrics-matter.qmd
        - 07-model-evaluation/02-how-precision-recall.qmd
        - 07-model-evaluation/03-what-confusion-matrix-f1.qmd
        - 07-model-evaluation/04-practice-compare-models.qmd
        - 07-model-evaluation/05-challenge.qmd
        - 08-explainable-ai/index.qmd
        - 08-explainable-ai/01-why-explainability.qmd
        - 08-explainable-ai/02-how-exploring-predictions.qmd
        - 08-explainable-ai/03-what-xai-shap-lime.qmd
        - 08-explainable-ai/04-practice-shap-plots.qmd
        - 08-explainable-ai/05-challenge-global-explanation.qmd
    - part: "第二部分：RAG与知识工程"
      chapters:
        - 09-rag-kickoff/index.qmd
        - 09-rag-kickoff/01-why-crisis.qmd
        - 09-rag-kickoff/02-how-rag-blueprint.qmd
        - 09-rag-kickoff/03-what-rag-concept.qmd
        - 09-rag-kickoff/04-practice-eda.qmd
        - 09-rag-kickoff/05-challenge.qmd
        - 10-embedding/index.qmd
        - 10-embedding/01-why-embedding.qmd
        - 10-embedding/02-how-embedding-geometry.qmd
        - 10-embedding/03-what-word-sentence-embedding.qmd
        - 10-embedding/04-practice-embedding.qmd
        - 10-embedding/05-challenge-visualize-embeddings.qmd
        - 11-vector-database/index.qmd
        - 11-vector-database/01-why-vector-db.qmd
        - 11-vector-database/02-how-ann.qmd
        - 11-vector-database/03-what-cosine-ann.qmd
        - 11-vector-database/04-practice-faiss.qmd
        - 11-vector-database/05-challenge-explore-indexes.qmd
        - 12-rag-pipeline/index.qmd
        - 12-rag-pipeline/12-1-why.qmd
        - 12-rag-pipeline/12-2-how.qmd
        - 12-rag-pipeline/12-3-what.qmd
        - 12-rag-pipeline/12-4-practice.qmd
        - 12-rag-pipeline/12-5-challenge-real-llm.qmd
        - 13-RAG-Optimization/index.qmd
        - 13-RAG-Optimization/13-1-why.qmd
        - 13-RAG-Optimization/13-2-how.qmd
        - 13-RAG-Optimization/13-3-what.qmd
        - 13-RAG-Optimization/13-4-practice.qmd
        - 13-RAG-Optimization/13-5-challenge.qmd
    - part: "第三部分：AI对齐工程"
      chapters:
        - 14-SFT/index.qmd
        - 14-SFT/14-1-why.qmd
        - 14-SFT/14-2-how.qmd
        - 14-SFT/14-3-what.qmd
        - 14-SFT/14-4-practice-sft.qmd
        - 14-SFT/14-5-challenge.qmd
        - 15-Reward-Modeling/index.qmd
        - 15-Reward-Modeling/15-1-why.qmd
        - 15-Reward-Modeling/15-2-how.qmd
        - 15-Reward-Modeling/15-3-what.qmd
        - 15-Reward-Modeling/15-4-practice-rm.qmd
        - 15-Reward-Modeling/15-5-challenge.qmd
        - 16-Alignment-PPO-DPO/index.qmd
        - 16-Alignment-PPO-DPO/16-1-why.qmd
        - 16-Alignment-PPO-DPO/16-2-how.qmd
        - 16-Alignment-PPO-DPO/16-3-what.qmd
        - 16-Alignment-PPO-DPO/16-4-practice.qmd
        - 16-Alignment-PPO-DPO/16-5-challenge.qmd
    - part: "第四部分：AI Agent工程"
      chapters:
        - 17-Arena-Evaluation/index.qmd
        - 17-Arena-Evaluation/17-1-why.qmd
        - 17-Arena-Evaluation/17-2-how.qmd
        - 17-Arena-Evaluation/17-3-what.qmd
        - 17-Arena-Evaluation/17-4-practice-arena.qmd
        - 17-Arena-Evaluation/17-5-challenge.qmd
        - 18-Agent-Foundation/index.qmd
        - 18-Agent-Foundation/18-1-why.qmd
        - 18-Agent-Foundation/18-2-how.qmd
        - 18-Agent-Foundation/18-3-what.qmd
        - 18-Agent-Foundation/18-4-practice.qmd
        - 18-Agent-Foundation/18-5-challenge.qmd
        - 19-Multi-Agent-Collaboration/index.qmd
        - 19-Multi-Agent-Collaboration/19-1-why.qmd
        - 19-Multi-Agent-Collaboration/19-2-how.qmd
        - 19-Multi-Agent-Collaboration/19-3-what.qmd
        - 19-Multi-Agent-Collaboration/19-4-practice.qmd
        - 19-Multi-Agent-Collaboration/19-5-challenge.qmd
        - 20-Agent-Reasoning-Safety/index.qmd
        - 20-Agent-Reasoning-Safety/20-1-why.qmd
        - 20-Agent-Reasoning-Safety/20-2-how.qmd
        - 20-Agent-Reasoning-Safety/20-3-what.qmd
        - 20-Agent-Reasoning-Safety/20-4-practice.qmd
        - 20-Agent-Reasoning-Safety/20-5-challenge.qmd
    - part: "终章：你的第一首AI交响曲"
      chapters:
        - 21-conclusion/index.qmd
        - 21-conclusion/01-journey-review.qmd
        - 21-conclusion/02-project-refactoring.qmd
        - 21-conclusion/03-future-outlook.qmd
        - 21-conclusion/04-epilogue.qmd
    - part: "附录"
      chapters:
        - references.qmd

page-footer:
  left: |
    机器学习：AI驱动的学习与应用
  right: |
    本书使用 Quarto 构建

bibliography: references.bib

lang: zh

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: false
    number-depth: 2
    code-fold: false
    code-tools: true
    code-copy: true
    highlight-style: github
    fig-width: 8
    fig-height: 6