project:
  type: book
  output-dir: docs

book:
  title: "机器学习：AI驱动的学习与应用"
  author: "陆海波 - 上海应用技术大学 经济与管理学院"
  date: "today"
  chapters:
    - index.qmd
    - part: "序章：新世界的生存法则"
      chapters:
        # 第1章 欢迎来到AI-First时代
        - 01-welcome/index.qmd
        - 01-welcome/01-not-another-ml-book.qmd
        - 01-welcome/02-ai-conductor.qmd
        - 01-welcome/03-learning-philosophy.qmd
        - 01-welcome/04-what-you-will-get.qmd
        # 第2章 本书使用指南与AI协同的艺术
        - 02-guide/index.qmd
        - 02-guide/01-golden-circle.qmd
        - 02-guide/02-prompt-engineering.qmd
        - 02-guide/03-first-ai-task.qmd
        - 02-guide/04-ai-learning-coach.qmd
        # 第3章 搭建你的AI协同开发环境
        - 03-environment/index.qmd
        - 03-environment/01-dev-environment.qmd
        - 03-environment/02-ai-copilot-config.qmd
        - 03-environment/03-install-libraries.qmd
    - part: "第一部分：传统机器学习 —— AIGC时代的新应用"
      chapters:
        # 第4章 项目启动：我们的AIGC产品需要一个"质检员"
        - 04-project-kickoff/index.qmd
        - 04-project-kickoff/01-why-crisis.qmd
        - 04-project-kickoff/02-how-what-mission.qmd
        - 04-project-kickoff/03-practice-eda.qmd
        - 04-project-kickoff/04-challenge-data-augmentation.qmd
        # 第5章 从文本到向量：教会机器"阅读"
        - 05-text-to-vectors/index.qmd
        - 05-text-to-vectors/01-why-machines-cant-read.qmd
        - 05-text-to-vectors/02-how-exploration-tfidf.qmd
        - 05-text-to-vectors/03-what-tfidf-concept.qmd
        - 05-text-to-vectors/04-practice-feature-engineering.qmd
        - 05-text-to-vectors/05-challenge-beyond-tfidf.qmd
        # 第6章 你的第一个分类器：AI内容"安检门"
        - 06-first-classifier/index.qmd
        - 06-first-classifier/01-why-first-inspector.qmd
        - 06-first-classifier/02-how-choose-model.qmd
        - 06-first-classifier/03-what-logistic-regression.qmd
        - 06-first-classifier/04-practice-train-predict-evaluate.qmd
        - 06-first-classifier/05-toolbox-ai-debug.qmd
        - 06-first-classifier/06-challenge-model-zoo.qmd
        # 第7章 "我的模型不够好？"——精通评估与迭代
        - 07-model-evaluation/index.qmd
        - 07-model-evaluation/01-why-metrics-matter.qmd
        - 07-model-evaluation/02-how-precision-recall.qmd
        - 07-model-evaluation/03-what-confusion-matrix-f1.qmd
        - 07-model-evaluation/04-practice-compare-models.qmd
        - 07-model-evaluation/05-toolbox-experiment-tracking.qmd
        - 07-model-evaluation/06-challenge-hyperparameter-tuning.qmd
        # 第8章 打开黑箱：让AI解释它的决策
        - 08-explainable-ai/index.qmd
        - 08-explainable-ai/01-why-explainability.qmd
        - 08-explainable-ai/02-how-exploring-predictions.qmd
        - 08-explainable-ai/03-what-xai-shap-lime.qmd
        - 08-explainable-ai/04-practice-shap-plots.qmd
        - 08-explainable-ai/05-challenge-global-explanation.qmd
    # - part: "第二部分：深度学习 —— 构建企业级LLM应用"
    #   chapters:
    #     # 第9章 项目启动：用RAG构建你的企业智能知识库
    #     - 09-rag-kickoff/index.qmd
    #     - 09-rag-kickoff/01-why-crisis.qmd
    #     - 09-rag-kickoff/02-how-rag-blueprint.qmd
    #     - 09-rag-kickoff/03-what-rag-concept.qmd
    #     - 09-rag-kickoff/04-toolbox-critical-thinking.qmd
    #     # 第10章 Embedding的魔力：让机器理解"意义"
    #     - 10-embedding/index.qmd
    #     - 10-embedding/01-why-embedding.qmd
    #     - 10-embedding/02-how-embedding-geometry.qmd
    #     - 10-embedding/03-what-word-sentence-embedding.qmd
    #     - 10-embedding/04-practice-embedding.qmd
    #     # 第11章 向量数据库：为你的AI建立一个"长期记忆"大脑
    #     - 11-vector-database/index.qmd
    #     - 11-vector-database/01-why-vector-db.qmd
    #     - 11-vector-database/02-how-ann.qmd
    #     - 11-vector-database/03-what-cosine-ann.qmd
    #     - 11-vector-database/04-practice-faiss.qmd
    #     # 第12章 串联成珠：搭建完整的RAG流程
    #     - 12-rag-pipeline/index.qmd
    #     - 12-rag-pipeline/1-why.qmd
    #     - 12-rag-pipeline/2-how.qmd
    #     - 12-rag-pipeline/3-what.qmd
    #     - 12-rag-pipeline/4-practice.qmd
    #     # 第13章 优化你的机器人：从"幻觉"到"忠实"
    #     - 13-RAG-Optimization/index.qmd
    #     - 13-RAG-Optimization/1-why.qmd
    #     - 13-RAG-Optimization/2-how.qmd
    #     - 13-RAG-Optimization/3-what.qmd
    #     - 13-RAG-Optimization/4-practice.qmd
    #     - 13-RAG-Optimization/5-challenge.qmd
    # - part: "第三部分：强化学习——训练自主决策的AI智能体"
    #   chapters:
    #     - 14-RL-Intro/index.qmd
    #     - 14-RL-Intro/1-why.qmd
    #     - 14-RL-Intro/2-how.qmd
    #     - 14-RL-Intro/3-what.qmd
    #     - 14-RL-Intro/4-why-learn-rl.qmd
        
    #     - 15-RL-Pricing-Bot/index.qmd
    #     - 15-RL-Pricing-Bot/1-why.qmd
    #     - 15-RL-Pricing-Bot/2-practice-simulator.qmd
    #     - 15-RL-Pricing-Bot/3-how-what-q-learning.qmd
    #     - 15-RL-Pricing-Bot/4-practice-training-viz.qmd
    #     - 15-RL-Pricing-Bot/5-challenge.qmd
        
    #     - 16-Agent-Bug-Fixer/index.qmd
    #     - 16-Agent-Bug-Fixer/1-why.qmd
    #     - 16-Agent-Bug-Fixer/2-design-sandbox.qmd
    #     - 16-Agent-Bug-Fixer/3-design-actions.qmd
    #     - 16-Agent-Bug-Fixer/4-design-rewards.qmd
    #     - 16-Agent-Bug-Fixer/5-practice-run-agent.qmd
    #     - 16-Agent-Bug-Fixer/6-challenge-alignment.qmd

    #     - 17-RL-Frontiers/index.qmd
    #     - 17-RL-Frontiers/1-recap.qmd
    #     - 17-RL-Frontiers/2-transfer.qmd
    #     - 17-RL-Frontiers/3-vision.qmd
        
    #     - 18-Epilogue/index.qmd
    #     - 18-Epilogue/1-summary.qmd
    #     - 18-Epilogue/2-ethics.qmd
    #     - 18-Epilogue/3-next-steps.qmd
    #     - 18-Epilogue/4-lifelong-learning.qmd
        
    #     - Appendix/A-AI-Dev-Best-Practice.qmd
    #     - Appendix/B-Gradio-Components.qmd

  
  page-footer:
    left: |
      机器学习：AI驱动的学习与应用
    right: |
      本书使用 Quarto 构建

bibliography: references.bib

lang: zh

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: false
    number-depth: 2
    code-fold: false
    code-tools: true
    code-copy: true
    highlight-style: github
    fig-width: 8
    fig-height: 6
    mermaid:
      theme: default



